name: gofast-0.1.0
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*  # Use Python 3.10 and newer versions
  - setuptools
  - scikit-learn>=1.1.2
  - cython>=0.29.33
  - h5py>=3.2.0
  - joblib>=1.2.0
  - matplotlib>=3.5.2
  - numpy>=1.23.0  
  - pandas>=1.4.0
  - scipy>=1.9.0
  - seaborn>=0.12.0
  - sqlalchemy
  - openpyxl>=3.0.3
  - pyproj>=3.3.0
  - pyyaml>=5.0.0
  - pytables>=3.6.1
  - threadpoolctl>=3.1.0
  - tqdm>=4.64.1
  - click>=8.0.4
  - statsmodels
  - docutils>=0.18.1
  - tensorflow>=2.15.0
  - pytest
